<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>TwoNMod3Search</RootNamespace>
		<AssemblyName>TwoNMod3Search</AssemblyName>
		<Nullable>disable</Nullable>
		<LangVersion>latest</LangVersion>
		<Optimize>true</Optimize>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
		<TieredCompilation>true</TieredCompilation>
		<TieredPGO>true</TieredPGO>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

</Project>